name: Test documentation

on:
    pull_request:

permissions:
  id-token: write
  pages: write

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ vars.WRITESIDE_INSTANCE }}
          artifact: ${{ vars.WRITESIDE_ARTIFACT }}
          docker-version: ${{ vars.WRITESIDE_DOCKER_VERSION }}
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ vars.WRITESIDE_ARTIFACT }}
            artifacts/report.json
          retention-days: 7

  test:
    name: Test docs
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ vars.WRITESIDE_INSTANCE }}
